opkg-keyrings: Document upgrading opkg-keyrings
ni/nilrt-docs pull request #72
Opened 2024-12-23 09:57 UTC by pratheekshasn

This PR adds documentation about opkg-keyrings and how to upgrade them on a target.

The document has been temporarily hosted [here](http://inrd-psn:8082/opkg-keyrings/opkg-keyrings_index.html), and can be reviewed.

[AB#2351694](https://ni.visualstudio.com/DevCentral/_workitems/edit/2351694)

# Testing
Build nilrt-docs.

2024-12-23 09:58 UTC, pratheekshasn commented
This is more of a draft as I haven't written the last section about SystemLink yet.

2025-01-24 22:18 UTC, chaitu236 requested changes
I see a lot of duplication of information across different sections and I think we can shorten the doc quite a bit.

2025-01-24 22:18 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * The package index (*Packages* file) lists all available packages and their
This wording makes it sound like the Packages file itself contains the signatures.. better to clarify.

2025-01-24 22:18 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +        or the package itself using the public key.
"or the package itself" - remove

2025-01-24 22:18 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * During package installation, opkg ensures that the signature matches one of the
Wording makes it sound like the signatures are string compared to key but they're cryptographically verified.
And is the feed's signature verified during package installation or just during `opkg update` operation? I know that package's md5/sha256sum are verified during package installation but that's not the same as "signatures matching trusted keys".

2025-01-24 22:18 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    wget https://download.ni.com/#ni-linux-rt/feeds/dist/Packages.gz.asc
Is this really the public key? My understanding is that this is just the signed data that would be different for files signed with same key.

The section makes it sound like you can download the public key from this file and add it to your system.. which I think is wrong.

2025-01-24 22:18 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +Click on the option to "Add/Remove software" on the target. On the upgrade tab, there should be an option to upgrade Opkg-Keyrings. Upgrading this package should do the trick and get the new signing
~~do the trick~~

2025-01-27 11:29 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +opkg signing is a mechanism to ensure the authenticity and integrity of .ipk
I have rephrased this.

2025-01-27 11:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +verify the authenticity and integrity of packages downloaded from a repository or feed.
I have rephrased this.

2025-01-27 11:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * A pair of private and public keys is created using a tool like gpg.
I have rephrased this.

2025-01-27 11:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * The package index (*Packages* file) lists all available packages and their
I have rephrased this.

2025-01-27 11:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +        or the package itself using the public key.
I have rephrased this.

2025-01-27 11:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * During package installation, opkg ensures that the signature matches one of the
I have rephrased this.

2025-01-27 11:31 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    wget https://download.ni.com/#ni-linux-rt/feeds/dist/Packages.gz.asc
Yes, I was wrong about this. I had been following this when I had manually signed the package index file while testing. I have removed this now.

2025-01-27 16:01 UTC, amstewart requested changes

2025-01-28 06:45 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +====================================================================
Fixed this now.

2025-01-28 20:40 UTC, amstewart requested changes

2025-01-28 20:49 UTC, chaitu236 requested changes
Just have a couple of small suggestions.

2025-01-28 20:49 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * The public key is preloaded or added to the system's trusted keyring, such as
Why does this need to be mentioned in "Verify Signature When a Feed is Updated" section?

2025-01-28 20:49 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +By upgrading the opkg-keyrings package, the system ensures its keyring remains up-to-date
> the system ensures its keyring remains

> seamlessly handling the addition

Seeing that we're asking the user to do upgrade the package manually, mentioning "seamless" is probably not accurate. I'd prefer if we just removed the whole line 152, 153.

2025-01-28 20:49 UTC, chaitu236 commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +Command Line:
We may want to mention that the update process through cmdline and MAX only works when system has BSI installed and is currently booted into runmode (as dist feed is only available on runmode).

2025-01-31 06:29 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    opkg upgrade opkg-keyrings
I have fixed this now.

2025-01-31 06:29 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +package on NI Linux Real-Time systems.
I have fixed this now.

2025-01-31 06:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * The public key is preloaded or added to the system's trusted keyring, such as
I have fixed this now.

2025-01-31 06:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +By upgrading the opkg-keyrings package, the system ensures its keyring remains up-to-date
I have removed this now.

2025-01-31 06:30 UTC, pratheekshasn commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +Command Line:
I have added this now.

2025-02-03 16:56 UTC, chaitu236 approved these changes

2025-02-03 17:05 UTC, amstewart approved these changes

2025-02-03 17:06 UTC, amstewart commented on docs/source/opkg-keyrings/opkg-keyrings_index.rst
> +    * The private key is used to sign the package index or individual packages
Fixed in latest.

2025-02-03 17:06 UTC, merged